sudo: true

dist: trusty 

env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

addons:
  chrome: stable

before_install:
  - openssl aes-256-cbc -K $encrypted_64814298f594_key -iv $encrypted_64814298f594_iv -in assets/server.key.enc -out assets/server.key -d  
  - wget -qO- $URL | tar xJf -
  - ./sfdx/install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - heroku plugins:install salesforce-lightning-cli
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_AUTOUPDATE_DISABLE=true
  - sfdx plugins:install salesforcedx
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername

script:
  - sfdx force:config:set apiVersion='41.0' --global
  - sfdx force:org:create -s -f config/project-scratch-def.json -a travisciorg
  - lintout=$(sfdx force:lightning:lint lightning-component-tests/main/default/aura/);if [[ $lintout =~ .*problem.*error.*warning ]]; then echo "$lintout"; false; fi
  - sfdx force:source:push -u travisciorg
  - sfdx force:lightning:test:run -a jasmineTests.app
  - sfdx force:lightning:test:run -a mochaTests.app
  - sfdx force:org:delete -u travisciorg -p
